title: Jimday's CF Homepage&ensp;|&ensp;民哥的CF主页
page-top-title: Jimday
top-section-bg-text: Jimday's Cloudflare Homepage！🎉<br>民哥的CF主页
home-subtitle: Jimday&ensp;|&ensp;民哥
copyright-text: '&copy; Jimday 2026. All Rights Reserved.'
